name: Portfolio Nextjs CI/CD

on:
  push:
    branches: [dev,staging,main]

env: 
  IMAGE_NAME: "${{secrets.DOCKER_USER }}/next-portfolio"
  DOCKER_USER: "${{secrets.DOCKER_USER}}"

jobs: 
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-actions@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASS}}

      - name: Build Docker Image 
        run: | 
         BRANCH=${echo "{GITHUB_REF#refs/heads/}"}
         docker build -t $IMAGE_NAME:$TAG .
         
      - name: Push image to Docker Hub
        run: | 
         BRANCH=$(echo "${GITHUB_REF#refs/heads/}")
         docker push $IMAGE_NAME:TAG


  deploy: 
    needs: build-push-image
    runs-on: self-hosted
    steps:
      - name: Deploy container on azure VM
        run: | 
          TAG=$(echo "${GITHUB_REF#refs/heads/}")
          IMAGE=${{secrets.DOCKER_USER}}/nextjs=portfolio:$TAG
          
          cd /var/www/portfolio

          sed "s|\$IMAGE_NAME|${{ secrets.DOCKER_USER }}/nextjs-portfolio|" docker-compose.prod.yml | \
          sed "s|\$TAG|$TAG|" > docker-compose.generated.yml

          docker compose -f docker-compose.generated.yml pull
          docker compose -f docker-compose.generated.yml up -d


          
        


